name: Cache Example Workflow

on:
  workflow_dispatch:  # run manually from GitHub Actions tab

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-d9751e1

      - name: prime-cache-d9751e1
        run: echo "Cache result: ${{ steps.cache.outputs.cache-hit }}"
